[package]
name = "homelab-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
async-trait = {workspace = true}
tonic = {workspace = true}
lapin = {workspace = true}
jsonwebtoken = {workspace = true}
reqwest = {workspace = true}
serde_json = {workspace = true}

derive-new = {workspace = true}
tokio = {workspace = true}
moka = {workspace = true}
thiserror = { workspace = true }